version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 1
    groups:
       actions-dependencies:
          patterns:
            - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 1
    groups:
       npm-dependencies:
          patterns:
            - "*"